### ISSUE TITLE
ссылка на rutracker не появляется

### ISSUE THREAD

**Issue by chumyshhh** [Malanavi/Watch-and-download-on-Shikimori#1]
``` JS
Uncaught (in promise) ReferenceError: browser is not defined
    at #createLink (userscript.html?name=Watch%2520and%2520download%2520on%2520Shikimori.user.js&id=c8cdd6a7-b809-4beb-b891-38f040d0a339:205:20)
    at #onViewChanged (userscript.html?name=Watch%2520and%2520download%2520on%2520Shikimori.user.js&id=c8cdd6a7-b809-4beb-b891-38f040d0a339:182:36)
    at HTMLDocument.<anonymous> (userscript.html?name=Watch%2520and%2520download%2520on%2520Shikimori.user.js&id=c8cdd6a7-b809-4beb-b891-38f040d0a339:164:75)
    at s.dispatch (turbolinks.js:71:40)
    at t.notifyApplicationAfterPageLoad (turbolinks.js:952:43)
    at t.visitCompleted (turbolinks.js:965:23)
    at e.complete (turbolinks.js:740:207)
    at e.<anonymous> (turbolinks.js:770:122)
    at turbolinks.js:820:40
```

**Comment by Malanavi** [comment]
Исправил 🤝
